# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Lost Ark Logger Repository
      uses: actions/checkout@v3
    
    - name: CheckoutMachina Repository
      uses: actions/checkout@v3
      with:
        repository: 'ravahn/machina'
        path: 'machina'
    
    - name: Setup Msbuild
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Restore Nuget Packages
      run: nuget restore LostArkLogger.sln
      
    - name: Build Solution
      run: msbuild LostArkLogger.sln /t:Clean,Build /p:platform="Any CPU"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./Bin/Debug
        asset_name: Debug.zip
        asset_content_type: application/zip
