# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Lost Ark Logger Repository
      uses: actions/checkout@v3
    
    - name: CheckoutMachina Repository
      uses: actions/checkout@v3
      with:
        repository: 'ravahn/machina'
        path: 'machina'
    
    - name: Setup Msbuild
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Restore Nuget Packages
      run: nuget restore LostArkLogger.sln
      
    - name: Build Solution
      run: msbuild LostArkLogger.sln /t:Clean,Build /p:platform="Any CPU";Configuration=Release
      
    - name: Import PFX
      shell: powershell
      run: |
        $pfxCertFilePath = Join-Path -Path $PSScriptRoot -ChildPath "CodeSigningCertificate.pfx"
        Set-Content -Value $([System.Convert]::FromBase64String($env:BASE64_PFX)) -Path $pfxCertFilePath -Encoding Byte
        $codeSigningCert = Import-PfxCertificate -FilePath $pfxCertFilePath -Password $($env:PFX_PASSWORD | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation Cert:\CurrentUser\My
      env:
        BASE64_PFX: ${{ secrets.CERTIFICATE }}
        PFX_PASSWORD: ${{ secrets.PASSWORD }}

    - name: Sign exe
      shell: powershell
      run: |
        $codeSigningCert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
        Set-AuthenticodeSignature -Certificate $codeSigningCert -FilePath "bin\Release\DpsMeter.exe" -TimestampServer "http://timestamp.digicert.com"
      
    - name: Create Release
      uses: ncipollo/release-action@v1.11.2
      with:
        artifacts: "./bin/Release/*.*"
        draft: true
        name: Release 
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
